### ISSUE TITLE
Subscriber Identity API

### ISSUE THREAD

**Issue by chrishowell** [camaraproject/IdentityAndConsentManagement#15]
There's been discussion around having an Anonymous Subscriber Identifier which was _truly_ anonymous, and so therefore couldn't be used in calls back to CSPs.

I propose that instead we have an Application Subscriber Identifier per ASP, so that any other party downstream of the CSP cannot derive the subscriber from the identifier, nor can they compare the identifier with any other party; however the CSP  can identify the subscriber from this identifier.

This would be fairly trival if the CSP 2-way encrypted rather than hashed the subscriber identity alongside an application identifier...

e.g. `enc( (marketplace_id +) application_id + imsi)`

There would be an API that took many possible true temporary/permanent identifiers, e.g. IP address, msisdn, external identifier

This could then be used as an input for other CAMARA APIs, rather than having each API have a set of of possible identifiers.

--- I'll make another proposal about using this identifier along with Consent scopes and a Certificate Authority to sign tokens - these could also be passed back via the other APIs to the CSP to validate that consent had been captured.

**Comment by tomvanpelt** [comment]
The proposed approach seems good. It might even allow to handle  a subscriber moving to a different network with number portability. For that it might be useful to have a standard response on the other CAMARA APIs to indicate that the used Application Subscriber Identifier is no longer valid. That could be augmented then with the possibility to invoke the API to obtain an Application Subscriber Identifier based on such an invalidated Application Subscriber Identifier. Assuming that the subscriber's old and new operators are federated, the former could obtain a new identifier from the latter then to provide to the ASP based on their knowledge of the true subscriber identity from the invalidated identifier.

**Comment by tomvanpelt** [comment]
Another aspect that could be covered might be levels of trust in the identification of the subscriber. Some of the suggested temporary identifiers would allow to identify the subscriber more reliably than others, e.g. when providing a public IP address and port, potentially the subscription providing a tethered connection could be identified rather than the device that is actually accessing the application service. For some of the CAMARA APIs such unreliable identification might be good enough while others could return a standard error indicating that a more reliable identification is required which should trigger the ASP to obtain a different identifier (e.g. the MSISDN after interacting with the subscriber) that could be used to invoke the API for obtaining the Application Subscriber Identifier again to obtain a more reliable version of that identifier that can be used with more of the other CAMARA APIs.

**Comment by hdamker** [comment]
As stated within the proposal discussion started by @MarkCornall in API_Backlog: we need to start with an user story for this API which describes the use cases and explicit also what should NOT be possible with this API and the provided identifier (e.g. tracking). It is also necessary to discuss on which legal basis this identifier can be issued (at least for the once who have to comply with GDPR) as there no such thing as an identifier which is not PII.

**Comment by MarkCornall** [comment]
@jpengar , Thank you for the comments above. TO pick up on the first questions
It's not intended for tracking, is it? No, how could it be? how would it be any different to a token?
Is this API expected to be consumed with client credentials? expected when IP is not sufficient to identify the subscriber device and MSISDN is not preferred as an initial parameter to identify a client.
As mentioned by @hdamker, the legal basis should be clarified. Will discuss today I am sure.
Is this API expected to provide a routable ID (with @ domain) to resolve home operator routing in federated scenarios? @ domain may provide personal information. 
@domain identifies you are one of many million people. I doubt this is personal. MSISDN is already thought of as personal information. @domain is also used in GPSI as standardised.

Telefonica proposals are good but all still rely on the client being on net to identify the client or the use of MSISDN in the initial call to identify the subscriber (as would an external user id in the first call unless MSISDN was used once). The community has stated that it would prefer not to use MISDN. 

Your proposal for renewing a token when offline may have legs. How do you allow that to happen when you then do not have any information to identify the subscriber except for an expired token and make that easy/transparent to the developer?

Telcofinder will work in any situation and will be needed to route to the correct operator in all situations where there is no direct contract, aggregator or federation.

I am sure we will discuss later

**Comment by jpengar** [comment]
> It's not intended for tracking, is it? No, how could it be? how would it be any different to a token?

I will refer here again to @hdamker [comment](https://github.com/camaraproject/WorkingGroups/pull/237#issuecomment-1582733067) that explains it much better than me xD

> Telefonica proposals are good but all still rely on the client being on net to identify the client or the use of MSISDN in the initial call to identify the subscriber (as would an external user id in the first call unless MSISDN was used once). The community has stated that it would prefer not to use MISDN.

Yes, what we propose is to perform IP-based authentication every time there is an observed mobile network IP address of the target device. But for other scenarios where there is no observed IP address (no mobile connection in the device, connection via WiFi, back-end based service with no front-end application in the target device,...) we propose to use MSISDN as a login hint for authentication.

We are not aware of any community preference not to use MSISDN, and in fact in previous CAMARA discussions it was stated that clients should not be prevented from using MSISDN if the MSISDN is already known by them.

**In any case, for those scenarios where there is no mobile IP address to identify the user/device, what would be the input parameter of the proposed Identity API to obtain this external ID?** Because as far as we understand, the external ID is also needed in these cases for routing and to use this ID in subsequent calls to the CAMARA APIs.

> Your proposal for renewing a token when offline may have legs. How do you allow that to happen when you then do not have any information to identify the subscriber except for an expired token and make that easy/transparent to the developer?

Usage of refresh tokens is OAuth standard and it ensures the security of access. The refresh token is used to obtain new access tokens without the need to re-authenticate the user, but you have already authenticated the user, you have already authorised the client App and you have already validated consents if applicable when obtaining the initial access token... The access_token you obtain will still be associated to the user you authenticated. The refresh token authenticity, integrity, and expiration is validated, the signature is checked, etc... Privacy and security is guaranteed. For developer perspective is as easy as sent a refresh token request to obtain a new access token.

**Comment by shilpa-padgaonkar** [comment]
https://github.com/camaraproject/WorkingGroups/pull/237#issuecomment-1590880621

**Comment by AxelNennker** [comment]
I would like adding to this discussion that OpenID and, of course, GSMA's own mobile connect have the concept of a pseudonymous customer reference or pairwise pseudonymous identifier (PPID).

https://openid.net/specs/openid-connect-core-1_0.html 
`Pairwise Pseudonymous Identifier (PPID) Identifier that identifies the Entity to a Relying Party that cannot be correlated with the Entity's PPID at another Relying Party.`

https://mobileconnect.io/wp-content/uploads/2019/02/MC-Authenticate-functional-data-sheet-FINAL-1.pdf 
`The Operator provides success or failure response back to the SP along with a pseudonymous customer reference (PCR) unique for each user:SP pairing (SP can use this PCR going forward for identifying a returning user or binding to an existing SP user account)`

PPID is used in other API's e.g. OpenId Client Initiated Backchannel Authentication:
https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0.html

The "External Identity" API proposal must clearly state the differences and benefits compared to OMA ACR, 3gpp's GPSI, OpenId Connect and Mobile Connect.

**Comment by chrishowell** [comment]
Happy Thursday everyone :)
Here's the _draft_ flow.. there's plenty more explaining to be done... but initial thoughts would be good.

![SubscriberIdentityApi](https://github.com/camaraproject/IdentityAndConsentManagement/assets/1407962/89dbd435-317a-4cbd-a0e1-5790e20e0112)

A couple of points:
1. It would be nicer to have a true subscriber identity, rather than msisdn in the subscriber token, so number rotation could never happen - but I leave that to you clever CSP chaps to discuss. It also doesn't need to be the same across all CSPs ;)
2. The timestamp is there to provide a pseudo-nonce, to prevent cross-app tracking, but it could also be used by each CSP to set their own expiries. It also doesn't need to be the same across all CSPs ;)
3. Number Verify (v3?) implementation with this approach is extremely trivial and doesn't require any redirects.. a call from the ASP to the CSP with an on-net subscriber token and hopefully the matching MSISDN would be all it took.
4. The CSP could choose to 'trust' on-net tokens a bit more than off-net tokens, and sometimes require an on-net token for some APIs.. again it doesn't need to be the same across all CSPs ;)
5. There doesn't need to be any auth on the on-net Subscriber Identity Function access, as its access is via private IP and the subscriber is obviously already known via other methods; though there could be rate limiting.

Lots of flexibility here.

The 'well-known' URL would be the same for all CSPs, meaning it could be baked into applications. The CSP would define an entry in their DNS that points to the private IP for their Subscriber Identity Function. Access from the ASP's app to the CSP's function would happen over their private network so the appropriate security/enrichments happen.

**Comment by chrishowell** [comment]
In an IoT environment, I assumed that an IoT device would have a 'home checkin', where it could publish it's subscriber id. I.e. I'd expect a console either that the consumer accessed directly, or via the manufacturer, where the IoT device could publish its on-net subscriber id to.

**Comment by jpengar** [comment]
@chrishowell I think we should focus proposals and discussions on the scope of CAMARA, which is the API definition. Surely an explanation flow may be needed, but for the sake of common understanding we should show flows in terms of API client and API server. The API server may be a CSP or a hyperscaler, but the API definition must be valid for both.

If useful or relevant, we may need to distinguish whether the API Client is a FrontEnd or BackEnd; also, if needed, it may be useful to refer to some API access-relevant points like restrictions/considerations on AuthN/AuthZ (this was done for example in Number Verification).
 
Also, as CAMARA has a focus on APIs, decisions on how to solve routing (e.g.: references to HLR) or architectural concepts such as Aggregator vs. CSP should not be in the scope of discussions. These should instead be discussed and agreed in the GSMA technical stream. 
 
It'd be great if you could adapt your proposal to a definition that fits this scope.

---

Below are Telefónica's comments on the proposed flow, but please let's continue the discussion in the appropriate forum vor each issue:

* The proposed flow is basically to move the Telco Finder logic to an external API with two required implementations: 1) "on-net" based on DNS resolution; and 2) "off-net" based on HLR lookup (which is not a generic solution, but a specific Vonage implementation). So this looks like shifting the routing complexity from the AuthN/AuthZ flows to another external non-standard flow, rather than simplifying access to the CAMARA APIs as a whole. Anyway, as already indicated, let's better discuss this 'routing' part in GSMA where entities and flows are discussed'

* To do this, the "on-net" routing version relies on a "csp-subscriber-function-private-ip" that requires the FE application to call an operator "API" and:
  - It pretends that this API is not secured at all, i.e. it leaves an unsecured API open for any third party application to obtain a user identifier and information about the operator providing the service to that user. This would require a security audit, but it doesn't seem acceptable from an operator security perspective. It looks like an attempt to implement a similar approach to the carrier tokens, based on an entitlement server, but without the necessary security mechanism in place. Because with a carrier token, security is guaranteed in the interaction with the entitlement server, and this functionality is not open to third-party applications on iOS and Android for good reason. Only for applications with carrier privileges... hopefully this will change in the future.
  - This API may require user consent as it provides personal user information. If so, how will consent be managed if the user has not even been authenticated? Access to personal information cannot be given lightly without specifying a purpose.
  - It also assumes that the application would use the operator's DNS to resolve the API endpoint, which can't be guaranteed.
  - Each operator would still have to resolve the mapping between the observed IP of the device and the corresponding MSISDN, so this DNS-based procedure is only an alternative to the IP-based routing that is standardised in the approved flows via Telco Finder. Obtaining a "Subscriber Token/ID" is not the goal of the flow, but only a means to resolve IP-based routing including a rootable domain. However, in the approved solution, a user pseudonym could be returned if necessary, so this particular aspect does not justify the change...  

* For the fallback to off-net, it's introduced a resolution through HLR, which is basically the particular implementation that Vonage has to resolve the destination operator through MSISDN. It is not something standardised for all aggregators/operators, Telco Finder is. This would not be a problem as long as it is clear that it is a particular mechanism of Vonage as an aggregator, alternative to Telco Finder which is the standard solution for this.

* It includes the AuthN/AuthZ flow against the operator as part of the Network API call.

* Could you explain exactly what the problems are with the standard Auth code FE flow approved and how this proposal solves them? Saying that the Auth code is complex because it has redirects does not seem to be a relevant argument against the approved FE flow, which guarantees security, privacy by design, is based on standards like OAuth and OIDC... (existing in production almost as is as mentioned by Orange). The proposed flow seems to be just an alternative for the IP based resolution of the target operator and not necessarily simpler, for example operations 21 to 24 are not detailed but they must be the BE flow already approved between Aggregator as BE and the Operator to get a 3-legged access token based on a BE OIDC flow and manage user consent accordingly. So in effect all the other previous messages are added to the existing approved BE flow.

**Comment by chrishowell** [comment]
> It pretends that this API is not secured at all, i.e. it leaves an unsecured API open for any third party application to obtain a user identifier and information about the operator providing the service to that user. This would require a security audit, but it doesn't seem acceptable from an operator security perspective. It looks like an attempt to implement a similar approach to the carrier tokens, based on an entitlement server, but without the necessary security mechanism in place. Because with a carrier token, security is guaranteed in the interaction with the entitlement server, and this functionality is not open to third-party applications on iOS and Android for good reason. Only for applications with carrier privileges... hopefully this will change in the future.
I don't see the need for authentication around this API, the API would only be available on the CSPs network

**Comment by chrishowell** [comment]
Some flows/examples without the Aggregator :)

![OffNet](https://github.com/camaraproject/IdentityAndConsentManagement/assets/1407962/aea11ba4-76cb-4bb3-b7b4-039d8b3850c9)
![OnNet](https://github.com/camaraproject/IdentityAndConsentManagement/assets/1407962/29f784e4-8c84-4123-98e2-648f3dd33d2e)

**Comment by chrishowell** [comment]
The Subscriber Identity token SHOULD have a nonce or pseudo-nonce (timestamp) and be encrypted with a 'secure' encryption algorithm, but the level of encryption and security of the token can/should be up to the CSP to decide based on the regulatory framework that they work within. There's no requirement for this to be the same across all CSPs.. 

If a nonce and secure encryption is used there should be no need to gather user consent to obtain this token, it's far far less sensitive than the IP address which the ASP has free access to. Importantly a token generated in this way cannot be used to perform cross-app tracking, as each request would return a different identifier.

**Comment by shilpa-padgaonkar** [comment]
From DT side, we would also like to reiterate the point that we cannot support this option, which tries to introduce the functionality offered by carrier tokens but without the guaranteed security offered by carrier tokens.

**Comment by jpengar** [comment]
From the TEF side, after internal assessment with our Privacy Guardian and Security teams, the alternative flow proposed [above](https://github.com/camaraproject/IdentityAndConsentManagement/issues/15#issuecomment-1624238873) **is not acceptable** from privacy and security perspective:
- Operator exposed APIs must be authenticated based on the OWASP Top Ten API (https://owasp.org/API-Security/editions/2023/en/0x11-t10/). An unauthenticated API as the first endpoint for managing access to operator services/resources would not comply with these API security practices.
- Anti-DDoS and brute force attack control mechanisms should be implemented on this endpoint to avoid potential abuse in the massive request for identifiers or undesirable behavior of the endpoint itself when exceeding its availability thresholds.
- There is processing of personal data, as the user is not directly identified, but is indirectly identifiable. The pseudonym uniquely identifies an operator user. The inclusion of the @ domain (not obfuscated) at the end would categorize the user of each operator and identify our customers.
- The purpose of the API requires a legal basis that legitimizes the use of this personal data.

**Comment by jpengar** [comment]
@chrishowell @tomvanpelt @shilpa-padgaonkar @AxelNennker and others

As agreed [in the last follow-up call (26 July)](https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/documentation/MeetingMinutes/MOM-2023-07-26.md), an AP `20230726-01` was raised to split the discussion of the Subscriber Identity API into several separate issues related to each specific use case identified for the API or points of misalignment. We expected that this would facilitate discussion and ultimately determine whether the Subscriber Identity API is actually required for any of the proposed use cases.

This AP has not yet been addressed, but during the summer holidays [Telefónica](https://github.com/camaraproject/IdentityAndConsentManagement/issues/15#issuecomment-1671290900) and [DT](https://github.com/camaraproject/IdentityAndConsentManagement/issues/15#issuecomment-1669956031) confirmed that they could not support the alternative flow proposed by Vonage. This was mainly related to the mentioned use case of having a routable user identifier, which could not be considered in the short to medium term, at least until a solution such as carrier tokens is available.

Regarding other use cases for the Subscriber Identity API, such as having a "standard" user identifier to be used in subsequent CAMARA API calls (avoiding to consider multiple formats IPv4, IPv6, MSISDN, etc), or a user identifier to be used for offline access to CAMARA APIs. 

**From Telefónica's perspective, using the OpenID standard as an identity layer on top of OAuth would simplify identity management and would not require the definition of an additional Subscriber Identity API**

Information such as IP address or MSISDN is resolved to the corresponding user identifier as part of the AuthN/authZ process. Finally, a 3-legged access_token is obtained that is already associated with the user identifier. For subsequent calls to CAMARA APIs, it wouldn't be necessary to provide an identifier in the API request, since the user identity is already associated with the access token.

Other scenarios mentioned, such as offnet scenarios, could also be solved by issuing refresh tokens. This would allow to get new access tokens even if the device IP has changed, if the device has no mobile connectivity and so on...

**So, given the current status and the fact that there has been no feedback from other WG participants, Telefónica propose to close this issue. And in case any CAMARA participant wants to further discuss a specific use case for a Subscriber Identity API, just open a new issue to have a clean and not "contaminated" discussion from scratch. Just following the procedure suggested by @hdamker in https://github.com/camaraproject/IdentityAndConsentManagement/issues/15#issuecomment-1582854132.**

**Comment by jpengar** [comment]
As agreed in yesterday's (24/08) follow-up call, the deadline for closing this issue will be 30/08 if there are no further comments/objections.

**Comment by jpengar** [comment]
As agreed in [23/08 follow-up meeting](https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/documentation/MeetingMinutes/MOM-2023-08-23.md) this issue is CLOSED as there are no further comments and no further objections.
