### ISSUE TITLE
Baseline - Using purpose parameter in the authorization request- - feedback

### ISSUE THREAD

**Issue by gmuratk** [camaraproject/IdentityAndConsentManagement#28]
**Problem description**
Suggested text edits and shared thoughts on Baseline #13 Using purpose parameter in the authorization request

**Expected action**

1.  “The application can include a list of..”  --  ‘include’ instead of ‘request’ seems more appropriate.
2.  “This parameter has been defined in these guidelines to allow applications to provide a purpose/s name which represents the reason why a client application needs to process a certain piece of user Personal Information.” -- ‘client’ term may be confusing as it may be understood strictly as the application on the end user device
3.  An API/path may enable access to multiple scopes of PI resources.  If an authorization is provided only a subset of scopes for that API/path, the purpose it was requested for, then I think authorization should not be granted.

**Additional context**
n/a

**Comment by jpengar** [comment]
Thanks for the feedback @gmuratk. Actually, we are going to commit a new change to remove the information in this section. Basically with the goal to leave 100% open for discussion how the purpose is provided in the authorisation request.

But this issue is really important, as more than one purpose can map to the same API resources/operations, as users may provide consent to access those API resources for a functional motive, but not for a commercial/advertising motive for example. Specifying the purpose in the authorisation request will allow the Auth Server to issue the appropriate access token only if the user's consent has been previously registered for the application client and for the requested purpose.
