### ISSUE TITLE
Inventory of Camara APIs indicating the consent type needed

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/IdentityAndConsentManagement#34]
**Problem description**
We currently do not have a document where we could check if a certain Camara API needs explicit consent or not. It would be important that this list is overseen by privacy and legal experts from the operator-teams.

**Expected action**
IMHO, it would be good to maintain a document in Camara (an inventory of sorts) where we have a list of Camara APIs and mention if an explicit consent is applicable or not. We could also enhance this with other supplementary information around consent, such as DataCategory: What kind of data? –  e.g. location (GPS coordinates) and 
List of possible Purposes: What is the data used for? e.g. Fraud management 

If we agree that such a document would be useful, we can create a PR for the same.

**Additional context**
N/A

**Comment by bigludo7** [comment]
@shilpa-padgaonkar Yes it makes sense to have this documentation.

In order to help, I have a listing of current API/scope defined (from the swagger). It provided some information as 2 or 3 leg usage is already defined for some API. Probably some API needs update (I guess device identifier for example need a scope)

**Number Verification** 

- no scope defined for the Camara version

- 2 scope for /authorize : `mc_vm_match` and `mc_vm_match_hash` – defined as a parameters

**OTP Validation**

- One scope defined for two_legged in securitySchemes :  `one-time-password-sms:send-validate`  

**SIMSwap**

- For CAMARA Version: 2 scopes defined for three_legged in securitySchemes: `check-sim-swap` and `retrieve-sim-swap-date`

- On scope for the MC version defined as parameter: `mc_atp`

**Device location**

- One scope defined for three_legged in securitySchemes : `device-location-read`

**Home device Qod**

- One scope defined for three_legged in security (not in securitySchemes): `home-devices-qod-qos-write`

**QualityOnDemand**

- No scope defined

**DeviceIdentifier**

- No scope defined

**AnonymisedSubscriberIdentifier**

- No scope defined

**Carrier Billing**

- Work in progress to merge both proposal – To be checked later.

**Device status**

- One scope defined for three_legged in securitySchemes : `device-status-roaming-read`

Traffic_Influence

- Two scopes defined for two_legged in securitySchemes : ` edge:traffic-influences:read` and   `edge:traffic-influences:write`

To be completed with other API from Edge Cloud family....

**Comment by shilpa-padgaonkar** [comment]
@jpengar : Yes, I do understand that consent will depend on the reason why the client application is accessing that API and processing the user's personal data.

 Regarding _"We should define and standardize the purposes allowed for CAMARA APIs, define what is the legal basis associated to each purpose, and finally we will see if an API requires consent or not depending on the purposes allowed for the API and the legal basis associated to those purposes."_

IMHO, it is easier to identify (and then standardize) the purposes and the legal basis associated with them, if we have the APIs (and the PIIs they make accessible) as an anchor point.  However, if you see it easier the other way around, I don't mind. 

But as long as this exercise produces a list identifying which APIs require consent depending on which purpose & legal basis, I am fine.

@bigludo7 : Thank you for the feedback and inputs.

**Comment by jpengar** [comment]
@shilpa-padgaonkar @bigludo7 first of all thank you both for your contribution :)

I just wanted to point out that the need of capture user consent will depend on the reason why the client application is accessing that API and processing the user's personal data. But I do see value in having a list of APIs and the PIIs they make accessible.

>@jpengar To be explicit, my point was not to recommend using current value but to get a view about what we have so far in the assets. Agreed with you that we must have a global agreement on this and then align accordingly APIs.

@bigludo7 We are aligned.
